theme: jekyll-theme-cayman

title: 不止日报
description: 小巧而丰富的阅读平台，聚合热门资讯平台消息，给你更加便捷的摸鱼体验。
show_downloads: true

github:
  apk_url: https://raw.githubusercontent.com/kutear/app-daily/gh-pages/bin/app-daily.apk
  is_project_page: false
